# **Taller importación, combinación y exportación de datos**


*   Andres Santiago Cristiano Trujillo
*   Katherin Alejandra Perez Martinez

In [2]:
# Para poder leer y abrir archivos de Excel
!pip install xlrd openpyxl

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [3]:
# Para trabajar datos tabulares
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **Punto 1**

In [4]:
#importamos librerías
import numpy as np
import pandas as pd
pd.__version__

'2.2.2'

# **Punto 2**

In [5]:
#MEJORAMOS LA VISUALIZACIÓN DE LOS DATA FRAMES

# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

# **Punto 3 y 4**

In [6]:
#IMPORTAMOS LOS ARCHIVOS DE DRIVE
import os

In [7]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
path = '/content/drive/MyDrive/GEIH 2025'

In [9]:
# Para establecer el directorio de los archivos
os.chdir(path)

In [10]:
ruta_julio = path + "julio/"

In [11]:
ruta_agosto = path + "Agosto/"

In [12]:
ruta_septiembre = path + "septiembre/"

In [13]:
ruta_octubre = path + "octubre/"

In [14]:
ruta_noviembre = path + "noviembre/"

In [15]:
ruta_diciembre = path + "diciembre/"

# **Punto 5**

# **Mes Julio**

In [16]:
df_GEIH_julio_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Julio 2025/Características generales, seguridad social en salud y educación.CSV", sep = ";")

In [17]:
df_GEIH_julio_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Julio 2025/Datos del hogar y la vivienda.CSV", sep= ";")

In [83]:
df_GEIH_julio_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Julio 2025/Fuerza de trabajo.CSV", sep = ";", encoding='latin1')

In [114]:
df_GEIH_julio_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Julio 2025/Ocupados.CSV", sep = ";", encoding='latin1', low_memory=False)

In [20]:
df_julio = pd.concat([df_GEIH_julio_características,df_GEIH_julio_hogar,df_GEIH_julio_fuerza,df_GEIH_julio_ocupados], axis= 1,)
df_julio

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27.75,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,731.00",7.00,"2,025.00","8,283,143.00",1.00,1.00,1.00,NaN,2.00,27.75,8.00,1.00,5.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,731.00",7.00,"2,025.00","8,283,143.00",1.00,1.00,1.00,NaN,2.00,27.75,8.00,1.00,5.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,731.00",7.00,"2,025.00","8,283,143.00",1.00,1.00,1.00,60.00,NaN,2.00,27.75,8.00,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00"
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27.75,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,"20,250,731.00",7.00,"2,025.00","8,283,145.00",1.00,1.00,1.00,NaN,2.00,59.11,8.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,250,731.00",7.00,"2,025.00","8,283,145.00",1.00,1.00,1.00,NaN,2.00,59.11,8.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,250,731.00",7.00,"2,025.00","8,283,145.00",1.00,1.00,1.00,60.00,NaN,2.00,59.11,8.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00"
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,59.11,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,731.00",7.00,"2,025.00","8,283,147.00",1.00,1.00,1.00,NaN,2.00,57.99,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,6.00,5.00,2.00,1.00,4.00,6.00,1.00,1.00,1.00,NaN,NaN,"30,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,7.00,"20,250,731.00",7.00,"2,025.00","8,283,147.00",1.00,1.00,1.00,NaN,2.00,57.99,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,6.00,5.00,2.00,1.00,4.00,6.00,1.00,1.00,1.00,NaN,NaN,"30,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,7.00,"20,250,731.00",7.00,"2,025.00","8,283,145.00",1.00,3.00,1.00,60.00,NaN,2.00,59.11,8.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00"
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,59.11,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,"20,250,731.00",7.00,"2,025.00","8,283,149.00",1.00,1.00,1.00,NaN,2.00,45.27,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"150,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,731.00",7.00,"2,025.00","8,283,149.00",1.00,1.00,1.00,NaN,2.00,45.27,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"150,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,731.00",7.00,"2,025.00","8,283,145.00",1.00,4.00,1.00,60.00,NaN,2.00,59.11,8.00,1.00,161.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"600,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"600,000.00",1.00,"7,200,000.00",3.00,NaN,10.00,2.00,12.00,42.00,NaN,NaN,42.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,6.00,7.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"600,000.00",1.00,161.00,"9,211.00"
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,59.11,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,731.00",7.00,"2,025.00","8,283,151.00",1.00,1.00,1.00,NaN,2.00,41.37,8.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,6.00,NaN,4.00,6.00,5.00,5.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,250,731.00",7.00,"2,025.00","8,283,151.00",1.00,1.00,1.00,NaN,2.00,41.37,8.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,6.00,NaN,4.00,6.00,5.00,5.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,250,731.00",7.00,"2,025.00","8,283,147.00",1.00,1.00,1.00,60.00,NaN,2.00,57.99,8.00,1.00,"5,022.00",1.00,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,6.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,3.00,1.00,1.00,1.00,0.00,84.00,4.00,NaN,3.00,NaN,1.00,20.00,"1,412.00","5,630.00",5.00,"1,200,000.00",2.00,7.00,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,1.00,NaN,1.00,"2,623,500.00",50.00,"5,022.00","9,122.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68431,20250731,7,2025,8316746,1,1,1,10,86.00,1,94.21,86,1,1,1,32,6.00,"1,993.00",1,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,1.00,4.00,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68432,20250731,7,2025,8316746,1,2,1,10,86.00,1,94.21,86,1,2,2,29,8.00,"1,996.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68433,20250731,7,2025,8316746,1,3,1,10,86.00,1,94.21,86,1,3,1,5,1.00,"2,020.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,3,4,4,2.00,1.00,1.00,1.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68434,20250731,7,2025,8316747,1,1,1,10,88.00,1,51.51,88,1,1,1,58,2.00,"1,967.00",1,2,NaN,3,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,1.00,1.00,"164,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68435,20250731,7,2025,8316747,1,2,1,10,88.00,1,51.51,88,1,2,2,55,7.00,"1,970.00",2,2,NaN,3,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,1.00,1,1.00,1.00,"140,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,411.00,5.00,411.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
print(df_julio.shape)
print(df_julio.columns)

(68436, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Mes Agosto**

In [22]:
import os

ruta = "/content/drive/MyDrive/GEIH 2025/Agosto 2025/"
print(os.listdir(ruta))

['No ocupados.CSV', 'Otros ingresos e impuestos.CSV', 'Otras formas de trabajo.CSV', 'Características generales, seguridad social en salud y\xa0 educación.CSV', 'Migración.CSV', 'Ocupados.CSV', 'Datos del hogar y la vivienda.CSV', 'Fuerza de trabajo.CSV']

In [23]:
df_GEIH_agosto_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Agosto 2025/Características generales, seguridad social en salud y\xa0 educación.CSV",sep =";")

In [24]:
df_GEIH_agosto_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Agosto 2025/Datos del hogar y la vivienda.CSV", sep=";")

In [84]:
df_GEIH_agosto_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Agosto 2025/Fuerza de trabajo.CSV", sep=";", encoding="latin1")

In [115]:
df_GEIH_agosto_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Agosto 2025/Ocupados.CSV", sep=";", encoding="latin1", low_memory=False)

In [27]:
df_agosto = pd.concat([df_GEIH_agosto_características, df_GEIH_agosto_hogar, df_GEIH_agosto_fuerza, df_GEIH_agosto_ocupados], axis=1)
df_agosto

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250835,8,2025,8316823,1,1,1,10,NaN,2,21.34,8,1,1,1,64,6.00,"1,961.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,10.00,4.00,731.00,2.00,NaN,2.00,1.00,1.00,"20,250,835.00",8.00,"2,025.00","8,316,823.00",1.00,1.00,1.00,NaN,2.00,21.34,8.00,1.00,1.00,4.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,2.00,1.00,4.00,2.00,3.00,4.00,1.00,NaN,NaN,"50,000,000.00","200,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,250,835.00",8.00,"2,025.00","8,316,823.00",1.00,1.00,1.00,NaN,2.00,21.34,8.00,1.00,1.00,4.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,2.00,1.00,4.00,2.00,3.00,4.00,1.00,NaN,NaN,"50,000,000.00","200,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,250,835.00",8.00,"2,025.00","8,316,823.00",1.00,1.00,1.00,60.00,NaN,2.00,21.34,8.00,1.00,"4,541.00",2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"900,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"900,000.00",1.00,"10,800,000.00",3.00,NaN,3.00,2.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,48.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,"900,000.00",45.00,"4,541.00","1,420.00"
1,20250835,8,2025,8316823,1,2,1,10,NaN,2,21.34,8,1,2,2,63,10.00,"1,961.00",2,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,1.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,"20,250,835.00",8.00,"2,025.00","8,316,824.00",1.00,1.00,1.00,NaN,2.00,21.32,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,2.00,1.00,4.00,4.00,NaN,NaN,NaN,"350,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,250,835.00",8.00,"2,025.00","8,316,824.00",1.00,1.00,1.00,NaN,2.00,21.32,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,2.00,1.00,4.00,4.00,NaN,NaN,NaN,"350,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,250,835.00",8.00,"2,025.00","8,316,824.00",1.00,1.00,1.00,60.00,NaN,2.00,21.32,8.00,1.00,"6,010.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,18.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"350,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,6.00,8.00,NaN,1.00,NaN,1.00,2.00,1.00,8.00,1.00,1.00,1.00,0.00,72.00,1.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,15.00,1.00,NaN,1.00,"1,773,500.00",60.00,"6,010.00","3,521.00"
2,20250835,8,2025,8316824,1,1,1,10,NaN,2,21.32,8,1,1,1,62,6.00,"1,963.00",1,3,NaN,3,NaN,2,2.00,2,5,NaN,NaN,1.00,1.00,2.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,835.00",8.00,"2,025.00","8,316,825.00",1.00,1.00,1.00,NaN,2.00,39.31,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,2.00,1.00,4.00,2.00,1.00,1.00,1.00,NaN,NaN,"40,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4.00,"20,250,835.00",8.00,"2,025.00","8,316,825.00",1.00,1.00,1.00,NaN,2.00,39.31,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,2.00,1.00,4.00,2.00,1.00,1.00,1.00,NaN,NaN,"40,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4.00,"20,250,835.00",8.00,"2,025.00","8,316,824.00",1.00,2.00,1.00,60.00,NaN,2.00,21.32,8.00,1.00,"9,700.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,72.00,3.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,1.00,2.00,NaN,1.00,NaN,1.00,2.00,1.00,6.00,2.00,2.00,1.00,0.00,24.00,3.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,2.00,NaN,30.00,1.00,NaN,1.00,"1,723,500.00",97.00,"9,700.00","9,111.00"
3,20250835,8,2025,8316824,1,2,1,10,NaN,2,21.32,8,1,2,2,50,1.00,"1,975.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,1.00,1.00,1.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,"20,250,835.00",8.00,"2,025.00","8,316,826.00",1.00,1.00,1.00,NaN,2.00,36.72,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,2.00,1.00,4.00,2.00,5.00,5.00,3.00,NaN,NaN,NaN,NaN,"300,000.00",NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,"20,250,835.00",8.00,"2,025.00","8,316,826.00",1.00,1.00,1.00,NaN,2.00,36.72,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,2.00,1.00,4.00,2.00,5.00,5.00,3.00,NaN,NaN,NaN,NaN,"300,000.00",NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,"20,250,835.00",8.00,"2,025.00","8,316,825.00",1.00,1.00,1.00,60.00,NaN,2.00,39.31,8.00,1.00,"3,312.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,108.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,360,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,50.00,NaN,NaN,7.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,9.00,1.00,1.00,1.00,0.00,24.00,4.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,40.00,8.00,NaN,1.00,"1,423,500.00",33.00,"3,312.00","7,127.00"
4,20250835,8,2025,8316825,1,1,1,10,NaN,2,39.31,8,1,1,1,30,4.00,"1,995.00",1,1,4.00,2,NaN,1,NaN,1,5,NaN,NaN,1.00,1.00,2.00,1,1.00,1.00,"56,920.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,"20,250,835.00",8.00,"2,025.00","8,316,827.00",1.00,1.00,1.00,NaN,2.00,34.78,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,2.00,2.00,1.00,4.00,2.00,1.00,4.00,4.00,NaN,NaN,NaN,"250,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4.00,"20,250,835.00",8.00,"2,025.00","8,316,827.00",1.00,1.00,1.00,NaN,2.00,34.78,8.00,1.00,1.00,2.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,2.00,2.00,1.00,4.00,2.00,1.00,4.00,4.00,NaN,NaN,NaN,"250,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4.00,"20,250,835.00",8.00,"2,025.00","8,316,825.00",1.00,3.00,1.00,60.00,NaN,2.00,39.31,8.00,1.00,"4,111.00",2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"900,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"900,000.00",1.00,"3,000,000.00",1.00,NaN,1.00,1.00,2.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,1.00,1.00,2.00,NaN,2.00,1.00,2.00,1.00,1.00,2.00,2.00,1.00,2.00,NaN,40.00,8.00,NaN,1.00,"900,000.00",41.00,"4,111.00","9,313.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68572,20250834,8,2025,8345514,1,1,1,10,18.00,1,65.14,18,1,1,2,43,7.00,"1,982.00",1,2,NaN,3,NaN,1,NaN,2,6,NaN,NaN,4.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68573,20250834,8,2025,8345514,1,2,1,10,18.00,1,65.14,18,1,1,1,11,11.00,"2,013.00",3,1,1.00,2,NaN,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,4.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68574,20250834,8,2025,8345515,1,1,1,10,50.00,1,366.46,50,1,1,1,45,8.00,"1,980.00",1,2,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,1.00,4.00,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,9.00,6.00,212.00,6.00,212.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68575,20250834,8,2025,8345515,1,2,1,10,50.00,1,366.46,50,1,2,2,39,2.00,"1,986.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68576,20250834,8,2025,8345515,1,3,1,10,50.00,1,366.46,50,1,2,2,8,4.00,"2,017.00",3,1,2.00,2,NaN,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
print(df_agosto.shape)
print(df_agosto.columns)

(68577, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Mes Septiembre**

In [29]:
df_GEIH_septiembre_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Septiembre 2025/Características generales, seguridad social en salud y educación.CSV", sep=";")

In [30]:
df_GEIH_septiembre_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Septiembre 2025/Datos del hogar y la vivienda.CSV", sep=";")

In [85]:
df_GEIH_septiembre_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Septiembre 2025/Fuerza de trabajo.CSV", sep=";", encoding="latin1")

/tmp/ipykernel_21676/2374776602.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_GEIH_septiembre_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Septiembre 2025/Fuerza de trabajo.CSV", sep=";", encoding="latin1")

In [116]:
df_GEIH_septiembre_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Septiembre 2025/Ocupados.CSV", sep=";", encoding="latin1", low_memory=False)

In [33]:
df_septiembre = pd.concat([df_GEIH_septiembre_características, df_GEIH_septiembre_hogar, df_GEIH_septiembre_fuerza, df_GEIH_septiembre_ocupados], axis=1)
df_septiembre

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250939,9,2025,8345569,1,1,1,10,NaN,2,26.60,8,1,1,1,59,5.00,"1,966.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,939.00",9.00,"2,025.00","8,345,569.00",1.00,1.00,1.00,NaN,2.00,26.60,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,939.00",9.00,"2,025.00","8,345,569.00",1.00,1.00,1.00,NaN,2.00,26.60,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,"20,250,939.00",9.00,"2,025.00","8,345,569.00",1.00,1.00,1.00,60.00,NaN,2.00,26.60,8.00,1.00,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,000,000.00",12.00,0.00,0.00,"960,000.00",0.00,"200,000.00",0.00,0.00,0.00,0.00,1.00,"100,000.00",2.00,NaN,NaN,NaN,2.00,NaN,NaN,2.00,NaN,"500,000.00",1.00,"6,000,000.00",2.00,NaN,9.00,2.00,12.00,56.00,NaN,NaN,56.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,3.00,NaN,1.00,"500,000.00",1.00,113.00,"6,111.00"
1,20250939,9,2025,8345569,1,2,1,10,NaN,2,26.60,8,1,2,2,62,9.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,1.00,2.00,1.00,"20,250,939.00",9.00,"2,025.00","8,345,570.00",1.00,1.00,1.00,NaN,2.00,54.03,8.00,1.00,7.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,250,939.00",9.00,"2,025.00","8,345,570.00",1.00,1.00,1.00,NaN,2.00,54.03,8.00,1.00,7.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,250,939.00",9.00,"2,025.00","8,345,570.00",1.00,2.00,1.00,60.00,NaN,2.00,54.03,8.00,1.00,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,468.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,200,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,050,000.00",1.00,"12,600,000.00",3.00,NaN,9.00,2.00,12.00,70.00,NaN,NaN,70.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,15.00,3.00,NaN,1.00,"1,050,000.00",1.00,113.00,"6,111.00"
2,20250939,9,2025,8345570,1,1,1,10,NaN,2,54.03,8,1,1,2,50,2.00,"1,975.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,"20,250,939.00",9.00,"2,025.00","8,345,571.00",1.00,1.00,1.00,NaN,2.00,43.73,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,250,939.00",9.00,"2,025.00","8,345,571.00",1.00,1.00,1.00,NaN,2.00,43.73,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,250,939.00",9.00,"2,025.00","8,345,570.00",1.00,3.00,1.00,60.00,NaN,2.00,54.03,8.00,1.00,220.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"300,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"300,000.00",1.00,"1,600,000.00",3.00,NaN,1.00,1.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"300,000.00",2.00,220.00,"6,210.00"
3,20250939,9,2025,8345570,1,2,1,10,NaN,2,54.03,8,1,2,1,63,4.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,250,939.00",9.00,"2,025.00","8,345,572.00",1.00,1.00,1.00,NaN,2.00,59.54,8.00,1.00,7.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,3.00,"20,250,939.00",9.00,"2,025.00","8,345,572.00",1.00,1.00,1.00,NaN,2.00,59.54,8.00,1.00,7.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,3.00,"20,250,939.00",9.00,"2,025.00","8,345,570.00",1.00,4.00,1.00,60.00,NaN,2.00,54.03,8.00,1.00,161.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,286.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"600,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"600,000.00",1.00,"7,200,000.00",3.00,NaN,9.00,2.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,8.00,NaN,10.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,18.00,3.00,NaN,1.00,"600,000.00",1.00,161.00,"9,211.00"
4,20250939,9,2025,8345570,1,3,1,10,NaN,2,54.03,8,1,3,1,19,10.00,"2,005.00",3,1,1.00,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,"20,250,939.00",9.00,"2,025.00","8,345,573.00",1.00,1.00,1.00,NaN,2.00,55.89,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,"20,250,939.00",9.00,"2,025.00","8,345,573.00",1.00,1.00,1.00,NaN,2.00,55.89,8.00,1.00,5.00,1.00,1.00,0.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,"20,250,939.00",9.00,"2,025.00","8,345,571.00",1.00,1.00,1.00,60.00,NaN,2.00,43.73,8.00,1.00,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,0.00,0.00,1.00,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"350,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"300,000.00",1.00,"3,600,000.00",3.00,NaN,3.00,2.00,12.00,35.00,2.00,NaN,35.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,5.00,NaN,1.00,"300,000.00",1.00,113.00,"6,111.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68258,20250939,9,2025,8374028,1,3,1,10,18.00,1,87.80,18,1,2,2,12,2.00,"2,013.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,4,4,4,1.00,1.00,2.00,4.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68259,20250939,9,2025,8374028,1,4,1,10,18.00,1,87.80,18,1,4,2,70,2.00,"1,955.00",4,3,NaN,3,NaN,1,NaN,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68260,20250939,9,2025,8374030,1,1,1,10,85.00,1,501.83,85,1,1,1,28,3.00,"1,997.00",1,2,NaN,2,NaN,1,NaN,2,6,NaN,NaN,3.00,1.00,2.00,1,1.00,1.00,"64,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,411.00,5.00,411.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68261,20250939,9,2025,8374030,1,2,1,10,85.00,1,501.83,85,1,2,2,33,12.00,"1,991.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,"70,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,11.00,2.00,"1,022.00",8.00,"1,022.00",1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68262,20250939,9,2025,8374030,1,3,1,10,85.00,1,501.83,85,1,2,1,2,8.00,"2,023.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
print(df_septiembre.shape)
print(df_septiembre.columns)

(68263, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Mes Octubre**

In [35]:
df_GEIH_octubre_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Octubre 2025/Características generales, seguridad social en salud y educación.CSV", sep=";")

In [36]:
df_GEIH_octubre_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Octubre 2025/Datos del hogar y la vivienda.CSV", sep=";", encoding='latin1')

In [117]:
df_GEIH_octubre_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Octubre 2025/Fuerza de trabajo.CSV", sep=";", encoding="latin1", low_memory=False)

In [38]:
df_GEIH_octubre_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Octubre 2025/Ocupados.CSV", sep=";", encoding="latin1")

/tmp/ipykernel_21676/1631749255.py:1: DtypeWarning: Columns (28,89,133,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df_GEIH_octubre_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Octubre 2025/Ocupados.CSV", sep=";", encoding="latin1")

In [39]:
df_octubre = pd.concat([df_GEIH_octubre_características, df_GEIH_octubre_hogar, df_GEIH_octubre_fuerza, df_GEIH_octubre_ocupados], axis=1)
df_octubre

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251044,10,2025,8374095,1,1,1,10,NaN,2,36.10,8,1,1,2,34,9.00,"1,991.00",1,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,1.00,1.00,"40,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,2.00,416.00,5.00,416.00,1.00,2.00,1.00,"20,251,044.00",10.00,"2,025.00","8,374,095.00",1.00,1.00,1.00,NaN,2.00,36.10,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,NaN,"530,000.00","180,000,000.00","150,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,3.00,"20,251,044.00",10.00,"2,025.00","8,374,095.00",1.00,1.00,1.00,NaN,2.00,36.10,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,NaN,"530,000.00","180,000,000.00","150,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,3.00,"20,251,044.00",10.00,"2,025.00","8,374,095.00",1.00,1.00,1.00,60.00,NaN,2.00,36.10,8.00,1.00,"6,512.00",1.00,2.00,2.00,4.00,2.00,1.00,1.00,"7,810.00",1.00,1.00,1.00,1.00,3.00,1.00,NaN,1.00,1.00,1.00,1.00,6.00,1.00,"2,000,000.00",2.00,NaN,1.00,"100,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"160,000.00",1.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"500,000.00",2.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,42.00,NaN,NaN,42.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,15.00,1.00,1.00,1.00,6.00,3.00,1.00,NaN,9.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,1.00,1.00,1.00,1.00,2.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,2.00,2.00,2.00,2.00,2.00,11.00,NaN,30.00,10.00,TRABAJO INDEPENDIENTE,1.00,"2,000,000.00",65.00,"6,512.00","3,321.00"
1,20251044,10,2025,8374095,1,2,1,10,NaN,2,36.10,8,1,2,1,30,10.00,"1,995.00",2,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,"20,251,044.00",10.00,"2,025.00","8,374,096.00",1.00,1.00,1.00,NaN,2.00,20.43,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,3.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"800,000.00","19,000,000.00","800,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,6.00,"20,251,044.00",10.00,"2,025.00","8,374,096.00",1.00,1.00,1.00,NaN,2.00,20.43,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,3.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"800,000.00","19,000,000.00","800,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,6.00,"20,251,044.00",10.00,"2,025.00","8,374,095.00",1.00,2.00,1.00,60.00,NaN,2.00,36.10,8.00,1.00,145.00,1.00,2.00,2.00,2.00,1.00,NaN,1.00,NaN,2.00,1.00,1.00,1.00,1.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"20,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,7.00,8.00,NaN,1.00,NaN,1.00,1.00,1.00,0.00,1.00,1.00,1.00,0.00,24.00,4.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,1.00,1.00,2.00,2.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,1.00,2.00,2.00,1.00,11.00,NaN,60.00,5.00,NaN,1.00,"1,423,500.00",1.00,145.00,"6,122.00"
2,20251044,10,2025,8374095,1,3,1,10,NaN,2,36.10,8,1,3,1,7,2.00,"2,018.00",3,1,1.00,2,NaN,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,"20,251,044.00",10.00,"2,025.00","8,374,097.00",1.00,1.00,1.00,NaN,2.00,32.41,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,1.00,1.00,1.00,1.00,1.00,1.00,3.00,4.00,NaN,NaN,NaN,"850,000.00",NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,"20,251,044.00",10.00,"2,025.00","8,374,097.00",1.00,1.00,1.00,NaN,2.00,32.41,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,1.00,1.00,1.00,1.00,1.00,1.00,3.00,4.00,NaN,NaN,NaN,"850,000.00",NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,"20,251,044.00",10.00,"2,025.00","8,374,096.00",1.00,1.00,1.00,60.00,NaN,2.00,20.43,8.00,1.00,"4,771.00",1.00,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,108.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"2,023,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,1.00,"126,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"600,000.00",1.00,1.00,"1,361,500.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,12.00,1.00,1.00,1.00,2.00,36.00,1.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,35.00,3.00,NaN,1.00,"2,023,500.00",47.00,"4,771.00","1,420.00"
3,20251044,10,2025,8374096,1,1,1,10,NaN,2,20.43,8,1,1,2,34,2.00,"1,991.00",1,1,6.00,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,"20,251,044.00",10.00,"2,025.00","8,374,098.00",1.00,1.00,1.00,NaN,2.00,34.27,8.00,1.00,1.00,4.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,3.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"300,000.00","200,000,000.00","500,000.00",NaN,1.00,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,4.00,"20,251,044.00",10.00,"2,025.00","8,374,098.00",1.00,1.00,1.00,NaN,2.00,34.27,8.00,1.00,1.00,4.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,3.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"300,000.00","200,000,000.00","500,000.00",NaN,1.00,NaN,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,4.00,"20,251,044.00",10.00,"2,025.00","8,374,096.00",1.00,2.00,1.00,60.00,NaN,2.00,20.43,8.00,1.00,"4,771.00",1.00,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,24.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,823,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,1.00,"126,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"400,000.00",1.00,1.00,"1,361,500.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,5.00,1.00,1.00,1.00,0.00,24.00,1.00,NaN,5.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,30.00,3.00,NaN,1.00,"1,823,500.00",47.00,"4,771.00","5,223.00"
4,20251044,10,2025,8374096,1,2,1,10,NaN,2,20.43,8,1,2,1,32,8.00,"1,993.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,1.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,729.00,5.00,729.00,2.00,1.00,1.00,"20,251,044.00",10.00,"2,025.00","8,374,099.00",1.00,1.00,1.00,NaN,2.00,32.21,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,2.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"900,000.00","180,000,000.00","600,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,5.00,"20,251,044.00",10.00,"2,025.00","8,374,099.00",1.00,1.00,1.00,NaN,2.00,32.21,8.00,1.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,3.00,1.00,1.00,4.00,2.00,1.00,1.00,1.00,1.00,1.00,3.00,2.00,NaN,"900,000.00","180,000,000.00","600,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,5.00,"20,251,044.00",10.00,"2,025.00","8,374,097.00",1.00,1.00,1.00,60.00,NaN,2.00,32.41,8.00,1.00,"4,923.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,2.00,1.00,1.00,1.00,1.00,1.00,NaN,1.00,1.00,1.00,1.00,3.00,1.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.00,72.00,NaN,NaN,72.00,NaN,NaN,8.00,7.00,NaN,1.00,NaN,1.00,2.00,1.00,6.00,1.00,1.00,1.00,1.00,2.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,2.00,11.00,NaN,30.00,5.00,NaN,1.00,"1,423,500.00",49.00,"4,923.00","4,321.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68705,20251044,10,2025,8403014,1,3,1,10,99.00,1,29.29,99,1,3,2,43,7.00,"1,982.00",3,1,1.00,1,2.00,1,NaN,1,1,510_05,NaN,6.00,NaN,NaN,1,1.00,1.00,"64,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,6.00,2.00,NaN,3.00,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68706,20251042,10,2025,8403015,1,1,1,10,91.00,1,169.63,91,1,1,2,38,8.00,"1,987.00",1,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68707,20251042,10,2025,8403015,1,2,1,10,91.00,1,169.63,91,1,2,1,35,3.00,"1,990.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68708,20251042,10,2025,8403015,1,3,1,10,91.00,1,169.63,91,1,3,1,16,12.00,"2,008.00",3,1,1.00,1,2.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,4.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68709,20251042,10,2025,8403015,1,4,1,10,91.00,1,169.63,91,1,4,2,12,6.00,"2,013.00",3,1,1.00,1,2.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,4.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
print(df_octubre.shape)
print(df_octubre.columns)

(68710, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Mes Noviembre**

In [41]:
df_GEIH_noviembre_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Noviembre 2025/Características generales, seguridad social en salud y educación.CSV", sep=";")

In [42]:
df_GEIH_noviembre_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Noviembre 2025/Datos del hogar y la vivienda.CSV", sep=";")

In [119]:
df_GEIH_noviembre_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Noviembre 2025/Fuerza de trabajo.CSV", sep=";", encoding="latin1", low_memory=False)

In [118]:
df_GEIH_noviembre_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Noviembre 2025/Ocupados.CSV", sep=";", encoding="latin1", low_memory=False)

In [45]:
df_noviembre = pd.concat([df_GEIH_noviembre_características, df_GEIH_noviembre_hogar, df_GEIH_noviembre_fuerza, df_GEIH_noviembre_ocupados], axis=1)
df_noviembre

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251148,11,2025,8403077,1,1,1,10,NaN,2,501.64,8,1,1,1,42,12.00,"1,982.00",1,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,4.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,251,148.00",11.00,"2,025.00","8,403,077.00",1.00,1.00,1.00,NaN,2.00,501.64,8.00,1.00,1.00,4.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,3.00,6.00,NaN,4.00,NaN,NaN,NaN,"50,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"20,251,148.00",11.00,"2,025.00","8,403,077.00",1.00,1.00,1.00,NaN,2.00,501.64,8.00,1.00,1.00,4.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,3.00,6.00,NaN,4.00,NaN,NaN,NaN,"50,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,"20,251,148.00",11.00,"2,025.00","8,403,077.00",1.00,1.00,1.00,60.00,NaN,2.00,501.64,8.00,1.00,"4,651.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,2.00,2.00,1.00,2.00,24.00,1.00,NaN,1.00,1.00,9.00,1.00,1.00,2.00,"1,600,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",1.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,8.00,8.00,NaN,1.00,NaN,1.00,1.00,1.00,2.00,1.00,1.00,1.00,0.00,156.00,3.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,30.00,1.00,NaN,1.00,"1,600,000.00",46.00,"4,651.00","5,414.00"
1,20251148,11,2025,8403079,1,1,1,10,NaN,2,501.64,8,1,1,1,38,8.00,"1,987.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,251,148.00",11.00,"2,025.00","8,403,079.00",1.00,1.00,1.00,NaN,2.00,501.64,8.00,1.00,1.00,4.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,2.00,1.00,4.00,3.00,1.00,1.00,4.00,NaN,NaN,NaN,"400,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,148.00",11.00,"2,025.00","8,403,079.00",1.00,1.00,1.00,NaN,2.00,501.64,8.00,1.00,1.00,4.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,2.00,1.00,4.00,3.00,1.00,1.00,4.00,NaN,NaN,NaN,"400,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,148.00",11.00,"2,025.00","8,403,079.00",1.00,1.00,1.00,60.00,NaN,2.00,501.64,8.00,1.00,145.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,15.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"400,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,50.00,NaN,NaN,50.00,NaN,NaN,2.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,12.00,24.00,7.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,1.00,2.00,2.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,"800,000.00",1.00,145.00,"6,122.00"
2,20251148,11,2025,8403081,1,1,1,10,NaN,2,680.00,8,1,1,1,45,11.00,"1,980.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,251,148.00",11.00,"2,025.00","8,403,081.00",1.00,1.00,1.00,NaN,2.00,680.00,8.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,2.00,1.00,4.00,9.00,1.00,3.00,5.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,251,148.00",11.00,"2,025.00","8,403,081.00",1.00,1.00,1.00,NaN,2.00,680.00,8.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,2.00,1.00,4.00,9.00,1.00,3.00,5.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,"20,251,148.00",11.00,"2,025.00","8,403,081.00",1.00,1.00,1.00,60.00,NaN,2.00,680.00,8.00,1.00,144.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,120.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"800,000.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,4.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,15.00,3.00,NaN,1.00,"1,100,000.00",1.00,144.00,"9,212.00"
3,20251148,11,2025,8403081,1,2,1,10,NaN,2,680.00,8,1,2,2,45,7.00,"1,980.00",2,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,"20,251,148.00",11.00,"2,025.00","8,403,082.00",1.00,1.00,1.00,NaN,2.00,266.16,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"420,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,251,148.00",11.00,"2,025.00","8,403,082.00",1.00,1.00,1.00,NaN,2.00,266.16,8.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"420,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,"20,251,148.00",11.00,"2,025.00","8,403,081.00",1.00,5.00,1.00,60.00,NaN,2.00,680.00,8.00,1.00,"2,395.00",1.00,1.00,NaN,NaN,1.00,NaN,2.00,NaN,2.00,2.00,2.00,2.00,12.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,1.00,3.00,3.00,3.00,6.00,NaN,NaN,"960,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"960,000.00",1.00,"17,200,000.00",3.00,NaN,1.00,2.00,12.00,45.00,NaN,NaN,45.00,NaN,NaN,3.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,24.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"960,000.00",23.00,"2,395.00","8,142.00"
4,20251148,11,2025,8403081,1,3,1,10,NaN,2,680.00,8,1,2,1,8,8.00,"2,017.00",3,1,2.00,1,1.00,1,NaN,1,6,NaN,NaN,NaN,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,3.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,"20,251,148.00",11.00,"2,025.00","8,403,084.00",1.00,1.00,1.00,NaN,2.00,555.78,8.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,1.00,3.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,251,148.00",11.00,"2,025.00","8,403,084.00",1.00,1.00,1.00,NaN,2.00,555.78,8.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,1.00,3.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,"20,251,148.00",11.00,"2,025.00","8,403,082.00",1.00,1.00,1.00,60.00,NaN,2.00,266.16,8.00,1.00,121.00,1.00,1.00,NaN,NaN,1.00,NaN,2.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"500,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"420,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,50.00,NaN,NaN,50.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,48.00,36.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,1.00,2.00,2.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"920,000.00",1.00,121.00,"9,211.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68577,20251148,11,2025,8435840,1,4,1,10,NaN,1,"1,068.21",25,1,4,1,71,3.00,"1,954.00",4,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,3.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68578,20251148,11,2025,8435840,1,5,1,10,NaN,1,"1,068.21",25,1,5,2,42,9.00,"1,983.00",6,1,3.00,1,4.00,2,2.00,2,6,NaN,NaN,4.00,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68579,20251148,11,2025,8435840,1,6,1,10,NaN,1,"1,068.21",25,1,6,2,17,11.00,"2,008.00",9,1,5.00,2,NaN,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68580,20251148,11,2025,8435840,1,7,1,10,NaN,1,"1,068.21",25,1,7,2,13,12.00,"2,012.00",9,1,5.00,2,NaN,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68581,20251148,11,2025,8435840,1,8,1,10,NaN,1,"1,068.21",25,1,5,2,8,10.00,"2,017.00",9,1,5.00,2,NaN,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
print(df_noviembre.shape)
print(df_noviembre.columns)

(68582, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Mes Diciembre**

In [47]:
import os

ruta = "/content/drive/MyDrive/GEIH 2025/Diciembre 2025/"
print(os.listdir(ruta))

['Características generales, seguridad social en salud y educación.CSV', 'Otros ingresos e impuestos.CSV', 'Fuerza\xa0de\xa0trabajo.CSV', 'Datos\xa0del hogar y\xa0la\xa0vivienda.CSV', 'Ocupados.CSV', 'Otras formas\xa0de\xa0trabajo.CSV', 'No ocupados.CSV', 'Migración.CSV']

In [48]:
df_GEIH_diciembre_características = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Diciembre 2025/Características generales, seguridad social en salud y educación.CSV", sep=";")

In [49]:
df_GEIH_diciembre_hogar = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Diciembre 2025/Datos\xa0del hogar y\xa0la\xa0vivienda.CSV", sep=";")

In [120]:
df_GEIH_diciembre_fuerza = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Diciembre 2025/Fuerza\xa0de\xa0trabajo.CSV", sep=";", encoding="latin1", low_memory=False)

In [121]:
df_GEIH_diciembre_ocupados = pd.read_csv("/content/drive/MyDrive/GEIH 2025/Diciembre 2025/Ocupados.CSV", sep=";", encoding="latin1", low_memory=False)

In [52]:
df_diciembre = pd.concat([df_GEIH_diciembre_características, df_GEIH_diciembre_hogar, df_GEIH_diciembre_fuerza, df_GEIH_diciembre_ocupados], axis=1)
df_diciembre

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251252,12,2025,8435963,1,1,1,10,NaN,2,101.66,8,1,1,1,32,6.00,"1,993.00",1,2,NaN,3,NaN,1,NaN,1,1,820_01,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,"20,251,252.00",12.00,"2,025.00","8,435,963.00",1.00,1.00,1.00,NaN,2.00,101.66,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,5.00,1.00,2.00,9.00,4.00,4.00,1.00,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,"20,251,252.00",12.00,"2,025.00","8,435,963.00",1.00,1.00,1.00,NaN,2.00,101.66,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,5.00,1.00,2.00,9.00,4.00,4.00,1.00,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,"20,251,252.00",12.00,"2,025.00","8,435,963.00",1.00,1.00,1.00,60.00,NaN,2.00,101.66,8.00,1.00,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,204.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,800,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,200,000.00",1.00,"10,000,000.00",3.00,NaN,1.00,1.00,9.00,90.00,NaN,NaN,90.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,8.00,2.00,1.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,20.00,2.00,1.00,1.00,2.00,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,1.00,9.00,NaN,5.00,8.00,NaN,1.00,"1,200,000.00",3.00,311.00,"6,223.00"
1,20251252,12,2025,8435963,1,2,1,10,NaN,2,101.66,8,1,2,2,28,11.00,"1,997.00",2,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,419.00,5.00,419.00,1.00,2.00,1.00,"20,251,252.00",12.00,"2,025.00","8,435,964.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,2.00,9.00,1.00,4.00,1.00,NaN,NaN,"500,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,964.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,2.00,9.00,1.00,4.00,1.00,NaN,NaN,"500,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,963.00",1.00,2.00,1.00,60.00,NaN,2.00,101.66,8.00,1.00,"5,611.00",2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,6.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,56.00,NaN,NaN,56.00,NaN,NaN,2.00,7.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,18.00,24.00,1.00,NaN,9.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,2.00,1.00,11.00,NaN,20.00,3.00,NaN,1.00,NaN,56.00,"5,611.00","9,412.00"
2,20251252,12,2025,8435963,1,3,1,10,NaN,2,101.66,8,1,2,1,0,5.00,"2,025.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"20,251,252.00",12.00,"2,025.00","8,435,965.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,2.00,9.00,2.00,4.00,5.00,NaN,NaN,NaN,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,965.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,6.00,NaN,2.00,9.00,2.00,4.00,5.00,NaN,NaN,NaN,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,964.00",1.00,1.00,1.00,60.00,NaN,2.00,78.40,8.00,1.00,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"2,000,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,500,000.00",1.00,"12,000,000.00",3.00,NaN,3.00,2.00,12.00,54.00,NaN,NaN,54.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,35.00,"5,223.00","4,711.00",4.00,"500,000.00",1.00,1.00,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,9.00,NaN,30.00,3.00,NaN,1.00,"2,000,000.00",3.00,311.00,"6,222.00"
3,20251252,12,2025,8435964,1,1,1,10,NaN,2,78.40,8,1,1,1,75,8.00,"1,950.00",1,3,NaN,3,NaN,2,2.00,2,5,NaN,NaN,2.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,251,252.00",12.00,"2,025.00","8,435,966.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,3.00,9.00,5.00,5.00,5.00,NaN,NaN,NaN,"40,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,966.00",1.00,1.00,1.00,NaN,2.00,78.40,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,3.00,9.00,5.00,5.00,5.00,NaN,NaN,NaN,"40,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,965.00",1.00,1.00,1.00,60.00,NaN,2.00,78.40,8.00,1.00,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"2,400,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,800,000.00",1.00,"19,600,000.00",3.00,NaN,9.00,2.00,12.00,48.00,NaN,NaN,48.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,9.00,NaN,25.00,3.00,NaN,1.00,"1,800,000.00",3.00,311.00,"6,222.00"
4,20251252,12,2025,8435965,1,1,1,10,NaN,2,78.40,8,1,1,1,68,11.00,"1,957.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,4.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,2.00,1.00,1.00,"20,251,252.00",12.00,"2,025.00","8,435,967.00",1.00,1.00,1.00,NaN,2.00,114.42,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,6.00,NaN,3.00,9.00,4.00,4.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,967.00",1.00,1.00,1.00,NaN,2.00,114.42,8.00,1.00,5.00,1.00,2.00,NaN,2.00,2.00,2.00,NaN,2.00,1.00,3.00,1.00,6.00,NaN,3.00,9.00,4.00,4.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1.00,"20,251,252.00",12.00,"2,025.00","8,435,966.00",1.00,1.00,1.00,60.00,NaN,2.00,78.40,8.00,1.00,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"3,000,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"2,400,000.00",1.00,"28,800,000.00",3.00,NaN,3.00,2.00,12.00,56.00,NaN,NaN,56.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,9.00,NaN,20.00,3.00,NaN,1.00,"2,400,000.00",3.00,311.00,"6,222.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66554,20251252,12,2025,8473907,1,1,1,10,NaN,2,378.31,73,1,1,2,61,6.00,"1,964.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66555,20251252,12,2025,8473908,1,1,1,10,54.00,1,534.55,54,1,1,1,58,3.00,"1,967.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,"120,000.00",4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66556,20251252,12,2025,8473908,1,2,1,10,54.00,1,534.55,54,1,2,2,51,3.00,"1,974.00",2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,"318,240.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66557,20251252,12,2025,8473908,1,3,1,10,54.00,1,534.55,54,1,3,2,31,2.00,"1,994.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,"178,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66558,20251252,12,2025,8473908,1,4,1,10,54.00,1,534.55,54,1,4,2,26,2.00,"1,999.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
print(df_diciembre.shape)
print(df_diciembre.columns)

(66559, 355)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=355)

# **Punto 6**

In [54]:
df_julio = df_julio.loc[:,~df_julio.columns.duplicated()]
df_agosto = df_agosto.loc[:,~df_agosto.columns.duplicated()]
df_septiembre = df_septiembre.loc[:,~df_septiembre.columns.duplicated()]
df_octubre = df_octubre.loc[:,~df_octubre.columns.duplicated()]
df_noviembre = df_noviembre.loc[:,~df_noviembre.columns.duplicated()]
df_diciembre = df_diciembre.loc[:,~df_diciembre.columns.duplicated()]
df_GEIH_2025 = pd.concat([df_julio,df_agosto,df_septiembre,df_octubre,df_noviembre,df_diciembre], axis=0, ignore_index=True)
df_GEIH_2025

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27.75,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,5.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00"
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27.75,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00"
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,59.11,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,6.00,5.00,2.00,1.00,4.00,6.00,1.00,1.00,1.00,NaN,NaN,"30,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,7.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00"
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,59.11,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"150,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,1.00,161.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"600,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"600,000.00",1.00,"7,200,000.00",3.00,NaN,10.00,2.00,12.00,42.00,NaN,NaN,42.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,6.00,7.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"600,000.00",1.00,161.00,"9,211.00"
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,59.11,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,6.00,NaN,4.00,6.00,5.00,5.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,1.00,"5,022.00",1.00,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,6.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,3.00,1.00,1.00,1.00,0.00,84.00,4.00,NaN,3.00,NaN,1.00,20.00,"1,412.00","5,630.00",5.00,"1,200,000.00",2.00,7.00,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,1.00,NaN,1.00,"2,623,500.00",50.00,"5,022.00","9,122.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,20251252,12,2025,8473907,1,1,1,10,NaN,2,378.31,73,1,1,2,61,6.00,"1,964.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409123,20251252,12,2025,8473908,1,1,1,10,54.00,1,534.55,54,1,1,1,58,3.00,"1,967.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,"120,000.00",4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409124,20251252,12,2025,8473908,1,2,1,10,54.00,1,534.55,54,1,2,2,51,3.00,"1,974.00",2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,"318,240.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409125,20251252,12,2025,8473908,1,3,1,10,54.00,1,534.55,54,1,3,2,31,2.00,"1,994.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,"178,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409126,20251252,12,2025,8473908,1,4,1,10,54.00,1,534.55,54,1,4,2,26,2.00,"1,999.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
print(df_GEIH_2025.shape)
print(df_GEIH_2025.columns)

(409127, 283)
Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=283)

# **Punto 7**

In [56]:
df_GEIH_2025.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=283)

In [57]:
CIIU = pd.read_excel("/content/drive/MyDrive/GEIH 2025/Estructura-detallada-CIIU-4AC-2022.xlsx", header=1)
CIIU

,División,Grupo,Clase,Descripción
0,SECCIÓN A,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P..."
1,01,NaN,NaN,"Agricultura, ganadería, caza y actividades de ..."
2,NaN,11.00,NaN,Cultivos agrícolas transitorios
3,NaN,NaN,111.00,"Cultivo de cereales (excepto arroz), legumbres..."
4,NaN,NaN,112.00,Cultivo de arroz
...,...,...,...,...
716,NaN,981.00,"9,810.00",Actividades no diferenciadas de los hogares in...
717,NaN,982.00,"9,820.00",Actividades no diferenciadas de los hogares in...
718,SECCIÓN U,NaN,NaN,ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTR...
719,99,NaN,NaN,Actividades de organizaciones y entidades extr...
720,NaN,990.00,"9,900.00",Actividades de organizaciones y entidades extr...

In [58]:
CIIU = CIIU[["Clase", "Descripción"]]

In [59]:
CIIU = CIIU.drop_duplicates(subset= "Clase")

In [60]:
CIIU.shape

(503, 2)

In [61]:
df_GEIH_2025["RAMA4D_R4"] = df_GEIH_2025["RAMA4D_R4"].astype(float)
CIIU['Clase']= CIIU['Clase'].astype(float)

In [62]:
df_GEIH_2025 = df_GEIH_2025.merge(
    CIIU,
    left_on="RAMA4D_R4",
    right_on="Clase",
    how="left")

In [63]:
df_GEIH_2025 = df_GEIH_2025.drop(columns=["Clase"])

In [64]:
df_GEIH_2025[["RAMA4D_R4","Descripción"]].head()

   RAMA4D_R4                            Descripción
0     143.00                Cría de ovejas y cabras
1     141.00       Cría de ganado bovino y bufalino
2     141.00       Cría de ganado bovino y bufalino
3     161.00  Actividades de apoyo a la agricultura
4   5,022.00            Transporte fluvial de carga

In [65]:
df_GEIH_2025.shape

(409127, 284)

# **Punto 8**

In [66]:
DIVIPOLA = pd.read_excel(
"/content/drive/MyDrive/IA Economia/Taller importación, combinación y exportación de datos/DIVIPOLA_Departamentos.xlsx",
header=None
)

In [67]:
DIVIPOLA.head(15)

         0             1
0   Código  Departamento
1        5     ANTIOQUIA
2        8     ATLÁNTICO
3       11  BOGOTÁ, D.C.
4       13       BOLÍVAR
5       15        BOYACÁ
6       17        CALDAS
7       18       CAQUETÁ
8       19         CAUCA
9       20         CESAR
10      23       CÓRDOBA
11      25  CUNDINAMARCA
12      27         CHOCÓ
13      41         HUILA
14      44    LA GUAJIRA

In [68]:
DIVIPOLA = DIVIPOLA[[0,1]]

In [69]:
DIVIPOLA.columns = ['DPTO','Departamento']

In [70]:
df_GEIH_2025['DPTO'] = df_GEIH_2025['DPTO'].astype(str)
DIVIPOLA['DPTO'] = DIVIPOLA['DPTO'].astype(str)

In [71]:
df_GEIH_2025 = df_GEIH_2025.merge(DIVIPOLA, on='DPTO', how='left')

In [72]:
df_GEIH_2025 = df_GEIH_2025.rename(columns={'Departamento_y':'Departamento'})

In [73]:
df_GEIH_2025.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO', 'RAMA2D_R4', 'RAMA4D_R4',
       'OFICIO_C8', 'Descripción', 'Departamento'],
      dtype='object', length=285)

# **Punto 9**

In [74]:
df_GEIH_2025.shape

(409127, 285)

In [75]:
duplicados = df_GEIH_2025.duplicated(
    subset=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    keep=False)

df_GEIH_2025[duplicados].shape

(0, 285)

In [76]:
df_GEIH_2025.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO', 'RAMA2D_R4', 'RAMA4D_R4',
       'OFICIO_C8', 'Descripción', 'Departamento'],
      dtype='object', length=285)

In [122]:
df_GEIH_2025

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,Descripción,Departamento
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27.75,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,5.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00",Cría de ovejas y cabras,ATLÁNTICO
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27.75,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,1.00,2.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,3.00,2.00,6.00,NaN,4.00,6.00,5.00,5.00,4.00,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00",Cría de ganado bovino y bufalino,ATLÁNTICO
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,59.11,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,6.00,5.00,2.00,1.00,4.00,6.00,1.00,1.00,1.00,NaN,NaN,"30,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,7.00,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00",Cría de ganado bovino y bufalino,ATLÁNTICO
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,59.11,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,1.00,1.00,2.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,2.00,1.00,2.00,1.00,4.00,9.00,5.00,5.00,4.00,NaN,NaN,NaN,"150,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.00,1.00,161.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"600,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"600,000.00",1.00,"7,200,000.00",3.00,NaN,10.00,2.00,12.00,42.00,NaN,NaN,42.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,6.00,7.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"600,000.00",1.00,161.00,"9,211.00",Actividades de apoyo a la agricultura,ATLÁNTICO
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,59.11,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,4.00,3.00,6.00,NaN,4.00,6.00,5.00,5.00,5.00,NaN,NaN,NaN,"60,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5.00,1.00,"5,022.00",1.00,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,6.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,3.00,1.00,1.00,1.00,0.00,84.00,4.00,NaN,3.00,NaN,1.00,20.00,"1,412.00","5,630.00",5.00,"1,200,000.00",2.00,7.00,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,1.00,NaN,1.00,"2,623,500.00",50.00,"5,022.00","9,122.00",Transporte fluvial de carga,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,20251252,12,2025,8473907,1,1,1,10,NaN,2,378.31,73,1,1,2,61,6.00,"1,964.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...",TOLIMA
409123,20251252,12,2025,8473908,1,1,1,10,54.00,1,534.55,54,1,1,1,58,3.00,"1,967.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,"120,000.00",4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...",NORTE DE SANTANDER
409124,20251252,12,2025,8473908,1,2,1,10,54.00,1,534.55,54,1,2,2,51,3.00,"1,974.00",2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,"318,240.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...",NORTE DE SANTANDER
409125,20251252,12,2025,8473908,1,3,1,10,54.00,1,534.55,54,1,3,2,31,2.00,"1,994.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,"178,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...",NORTE DE SANTANDER
409126,20251252,12,2025,8473908,1,4,1,10,54.00,1,534.55,54,1,4,2,26,2.00,"1,999.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y P...",NORTE DE SANTANDER

In [80]:
df_GEIH_2025.to_csv(
"/content/drive/MyDrive/IA Economia/Taller importación, combinación y exportación de datos/GEIH_2025.csv",
index=False
)